##model params
model_name : softmax
backbone: resnet50
loss    : softmax
criterion: crossentropy

#-------------------
weight_path: {
        "cosface":"/home/k64t/face_recognition/save/cosface_s64/ckpt/cosface_s64_32.pth",
        "arcface":"/home/k64t/face_recognition/save/arcface_s64/ckpt/arcface_s64_32.pth",
        "magface":"/home/k64t/face_recognition/save/magface_s64/ckpt/magface_s64_32.pth" #30
        }
module: {
        "cosface":"ir_se", 
        "arcface":"ir_se",
        "magface":"ir_se"
        }
mode : "soft"
#-------------------
##input config
image_size: 112
embd_size: 512
class_num: 10572
sample_num: 490623

##-------------------
## hyper params
weight_decay: !!float 5e-4
logits_scale: 64
logits_margin: 0.5
drop_ratio: 0.5
##-------------------
##optimizer
optimizer: SGD
momentum: 0.9
base_lr : 0.01
lr_steps: [18, 28] #epoch

# # ##--------------------
# # ## run params
batch_size: 128
init_epoch: 0
epoch_num: 32
step_per_save: 500
# # # paths
train_data: "/home/k64t/face_recognition/data/images_list.txt"
valid_data: {"lfw":"/home/k64t/face_recognition/data/lfw_pair.txt", 
        'cf_pf':"/home/k64t/face_recognition/data/cfp_fp_pair.txt", 
        'agedb30':"/home/k64t/face_recognition/data/agedb_30_pair.txt",
        'calfw': '/home/k64t/face_recognition/data/calfw_pair.txt',
        'cplfw': '/home/k64t/face_recognition/data/cplfw_pair.txt'}
# # test_data: ""
